language: c

addons:
    apt:
        packages:
            - git
            - bsdtar
            - libtool
            - automake
            - autoconf
            - autoconf-archive
            - libreadline-dev
            - libssl-dev

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

before_install:
    - .travis/before_install.sh

before_script:
    - .travis/before_script.sh

script:
    - .travis/script.sh

after_success:
    - ssh-agent .travis/after_success.sh

env:
    - BUILD_MAKEARGS='check' BUILD_PLATFORM='unix' BUILD_MAKEPATH='build'
    - BUILD_MAKEARGS='distcheck' BUILD_PLATFORM='unix' BUILD_MAKEPATH='build'
