#!/bin/sh

die() {
	echo fatal error $*
	exit -1
}

set -x

BASE="$1"

[ -n "$BASE" ] || BASE="master"


./update-autoconf ${BASE} autoconf/${BASE} || die

git branch -f autoconf/${BASE} __AUTOCONF_HEAD || die

git branch -D __AUTOCONF_HEAD

[ -n "${NO_PUSH}" ] && exit 0

read -p "Press enter to push." || exit 0

git push origin autoconf/${BASE}:autoconf/${BASE} || die

