#!/bin/sh

die() {
	echo fatal error $*
	exit -1
}

set -x


[ -d smcp ] && rm -fr smcp

git clone .git smcp || die
cd smcp || die
git checkout master || die
REV=`git describe --tags --always`
./bootstrap.sh || die
rm -fr autom4te.cache || die
git add . -f || die
git stash || die
git checkout master-autoconf || die
git rm . -f -r || die
git stash pop || die
git commit -m "Updated from $REV" || die


git push -f || die

cd .. || die

rm -fr smcp || die

git push origin master-autoconf || die
